### ISSUE TITLE
What is  the destination of  'AdbStream object corresponding to the specified destination'?

### ISSUE THREAD

**Issue by emptywalker** [tananaev/adblib#15]
I'm doubt about what is destination at `AdbConnection$open(String destination)` , the code:
```

/**
   * Opens an AdbStream object corresponding to the specified destination.
   * This routine will block until the connection completes.
   *
   * @param destination The destination to open on the target
   * @return AdbStream object corresponding to the specified destination
   * @throws UnsupportedEncodingException If the destination cannot be encoded to UTF-8
   * @throws IOException                  If the stream fails while sending the packet
   * @throws InterruptedException         If we are unable to wait for the connection to finish
   */
public AdbStream open(String destination) throws UnsupportedEncodingException, IOException, InterruptedException {

}

```

i don't clearly that how many `the specified destination` ;  I want to execute `adb forward tcp:$port localabstract: $remotePort`,  what should I set destination ?  why ?

**Comment by MuntashirAkon** [comment]
See Local Services section in the documentation: https://android.googlesource.com/platform/system/core/+/5aa0e4241029c80617a8e98b07f7f48ab6b3a3d7/adb/SERVICES.TXT

**Comment by wjj1928** [comment]
Anyone make forward work? I try `adb.open("forward:tcp:1234:tcp:1234")` but it report exception.

**Comment by mirfatif** [comment]
> Anyone make forward work? I try `adb.open("forward:tcp:1234:tcp:1234")` but it report exception.

It should be `forward:tcp:1234;tcp:1234`. Note the semicolon separator.
[Reference](https://android.googlesource.com/platform/packages/modules/adb/+/refs/tags/android-14.0.0_r1/SERVICES.TXT#92)

**Comment by wjj1928** [comment]
Changed that but still the same:
```
02-08 10:08:44.311 16802 16890 I MyExam  : forward:tcp:1234;tcp:1234
02-08 10:08:44.329 16802 16890 E AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
02-08 10:08:44.329 16802 16890 E AndroidRuntime: Process: com.sample.atest, PID: 16802
02-08 10:08:44.329 16802 16890 E AndroidRuntime: java.lang.RuntimeException: java.net.ConnectException: Stream open actively rejected by remote peer
02-08 10:08:44.329 16802 16890 E AndroidRuntime: 	at com.sample.atest.Adb$1.run(Adb.java:100)

```

**Comment by zwc456baby** [comment]
> Changed that but still the same:
> 
> ```
> 02-08 10:08:44.311 16802 16890 I MyExam  : forward:tcp:1234;tcp:1234
> 02-08 10:08:44.329 16802 16890 E AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
> 02-08 10:08:44.329 16802 16890 E AndroidRuntime: Process: com.sample.atest, PID: 16802
> 02-08 10:08:44.329 16802 16890 E AndroidRuntime: java.lang.RuntimeException: java.net.ConnectException: Stream open actively rejected by remote peer
> 02-08 10:08:44.329 16802 16890 E AndroidRuntime: 	at com.sample.atest.Adb$1.run(Adb.java:100)
> ```

Is this solved?
